spring:
  application:
    name: UserAccountServices

server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka # Springboot Eureka Server
      #defaultZone: http://localhost:9005/eureka/v2 # Docker 1.3.1 Eureka Server

